export const rawColors = {
  pdnBlueDark: '#0B2F51',
  pdnBluePrimary: '#7a3e7c',
  pdnBlueMedium: '#613962',
  pdnBlueLight: '#3B82F6',
  pdnCoral: '#d97f6f',
  pdnCoralLight: '#f29888',
  pdnCoralDark: '#c4695a',
  slate50: '#F8FAFC',
  slate200: '#E2E8F0',
  red500: '#ef4444',
  white: '#ffffff',
} as const;

export const colorTokens = {
  pdnBlueDark: 'var(--color-pdn-blueDark)',
  pdnBluePrimary: 'var(--color-pdn-bluePrimary) !important',
  pdnBlueMedium: 'var(--color-pdn-blueMedium)',
  pdnBlueLight: 'var(--color-pdn-blueLight)',
  pdnCoral: 'var(--color-pdn-coral)',
  pdnCoralLight: 'var(--color-pdn-coralLight)',
  pdnCoralDark: 'var(--color-pdn-coral-dark)',
  pdnBrandGradient: 'var(--gradient-pdn-brand)',
  pdnCoralGradient: 'var(--gradient-pdn-coral)',
  slate50: 'var(--color-ui-slate-50)',
  slate200: 'var(--color-ui-slate-200)',
  slate400: 'var(--color-ui-slate-400)',
  slate500: 'var(--color-ui-slate-500)',
  slate600: 'var(--color-ui-slate-600)',
  orange400: 'var(--color-ui-orange-400)',
  red500: 'var(--color-ui-red-500)',
  red200: 'var(--color-ui-red-200)',
  green800: 'var(--color-ui-green-800)',
  white: 'var(--color-ui-white)',
  white90: 'var(--color-ui-white-90)',
  white80: 'var(--color-ui-white-80)',
  white75: 'var(--color-ui-white-75)',
  white10: 'var(--color-ui-white-10)',
  black10: 'var(--color-ui-black-10)',
  black20: 'var(--color-ui-black-20)',
  black25: 'var(--color-ui-black-25)',
  black32: 'var(--color-ui-black-32)',
  bluePrimary04: 'var(--color-pdn-bluePrimary-04)',
  bluePrimary20: 'var(--color-pdn-bluePrimary-20)',
  coral30: 'var(--color-pdn-coral-30)',
  coral40: 'var(--color-pdn-coral-40)',
  red20: 'var(--color-ui-red-20)',
} as const;
